# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OpenRAN Gym
tagline: #
description: OpenRAN Gym
baseurl: # the subpath of your site, e.g. /support
url: https://openrangym.com # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: # Define whether this is a knowledge base, help center, or something else
use_authors: false #Set this to false to disable showing post authors

brand_logo: logo.png
favicon: favicon.ico
brand_name: OpenRAN Gym
header: OpenRAN Gym
subheader: An Open Toolbox for Data Collection and Experimentation with AI in O-RAN
short_description: "OpenRAN Gym is the first publicly-available research platform for
data-driven O-RAN experimentation at scale. Building on frameworks for data collection
and RAN control, OpenRAN Gym enables end-to-end design and testing of data-driven xApps
by offering an O-RAN-compliant near-real-time RIC and E2 termination."

footer_images:
  - image: other/NU_IoT_NLuxPlus_WRWW.png
    link: https://www.northeastern.edu/wiot/

home_image: /assets/post-assets/openrangym-architecture.png
meta_image: /post-assets/openrangym-architecture.png

# Social Links
twitter_username: #
facebook_page: #
github_username: #
email: mailto:melodia@northeastern.edu?cc=m.polese@northeastern.edu,s.doro@northeastern.edu,bonati.l@northeastern.edu&subject=[OpenRAN Gym]
linkedin_page: https://www.linkedin.com/company/institute-for-the-wireless-internet-of-things-at-northeastern-university/
instagram_username: #

# Template options
show_article_counter: false

# Navivation
nav_items:
  - name: Open5G
    link: https://open5g.info/
    external: true
  - name: Publications
    link: /other/publications
    external: false

nav_button: Contribute
nav_button_link: /other/contribute

# More Help
help_one_title: #
help_one_content: #
help_one_button: #
help_one_link: #

help_two_title: #
help_two_content: #
help_two_button: #
help_two_link: #

footer_items:
  - name: About
    link: /other/about
  - name: WiNES Lab
    link: https://ece.northeastern.edu/wineslab/
  - name: Northeastern Institute for the Wireless Internet of Things
    link: https://www.northeastern.edu/wiot/

# Build settings
theme: minima
# plugins:
#   - jekyll-feed
#   - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
